In [9]:
import numpy as np
import random

In [2]:
class Network(object): 
    def __init__(self, sizes): 
        self.num_layers = len(sizes) 
        self.sizes = sizes 
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]] 
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

In [3]:
net=Network([2,3,4])

In [5]:
#weights and biases between the first layer and second layer
net.biases[0],net.weights[0]

(array([[ 1.04394592],
        [-0.12173356],
        [ 0.03161153]]),
 array([[-1.23324519,  1.98440712],
        [-1.67773776, -0.91265633],
        [-0.05706997, -0.55824717]]))

In [6]:
#weights and biases between the second and third layer
net.biases[1],net.weights[1]

(array([[ 0.01539314],
        [-0.1911856 ],
        [ 1.05093934],
        [ 0.20771322]]),
 array([[ 0.46469115, -0.55479091,  0.89856444],
        [-0.15739892,  0.42872988,  0.13807433],
        [-0.26352866, -2.14988164, -0.53246011],
        [ 0.67310892,  1.27448871, -0.68321394]]))

In [7]:
net.weights[2]

IndexError: list index out of range

In [ ]:
def sigmoid(z):
    return 1/(1.0+np.exp(z))

In [ ]:
def feedforward(self,a):
    for b,w in zip(self.biases,self.weights):
        a=sigmoid(np.dot(a,w)+b)
    return a

In [10]:
def SGD(self,training_data,epochs,mini_batch_size,eta,test_data=None):
    if test_data:
        n_test=len(test_data)
    n=len(training_data)
    for j in range(epochs):
        random.shuffle(training_data)
        mini_batches=[
            training_data[k:k+mini_batch_size]
            for k in range(0,n,mini_batch_size)
        ]
        for mini_batch in mini_batches:
            self.update_mini_batch(mini_batch,eta)
        if test_data:
            print("Epoch {0}:{1}/{2}".format(j,self.evaluate(test_data),n_test))
        else:
            print("Epoch {0} is complete".format(j))

In [ ]:
def update_mini_batch(self,mini_batch,eta):
    nabla_b=[np.zeros(b.shape) for b in self.biases]
    nabla_w=[np.zeros(w.shape) for w in self.weights]