In [6]:
import numpy as np
import random
import tensorflow

In [2]:
class Network(object): 
    def __init__(self, sizes): 
        self.num_layers = len(sizes) 
        self.sizes = sizes 
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]] 
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

In [3]:
net=Network([2,3,4])

In [5]:
#weights and biases between the first layer and second layer
net.biases[0],net.weights[0]

(array([[ 1.04394592],
        [-0.12173356],
        [ 0.03161153]]),
 array([[-1.23324519,  1.98440712],
        [-1.67773776, -0.91265633],
        [-0.05706997, -0.55824717]]))

In [6]:
#weights and biases between the second and third layer
net.biases[1],net.weights[1]

(array([[ 0.01539314],
        [-0.1911856 ],
        [ 1.05093934],
        [ 0.20771322]]),
 array([[ 0.46469115, -0.55479091,  0.89856444],
        [-0.15739892,  0.42872988,  0.13807433],
        [-0.26352866, -2.14988164, -0.53246011],
        [ 0.67310892,  1.27448871, -0.68321394]]))

In [7]:
net.weights[2]

IndexError: list index out of range

In [ ]:
def sigmoid(z):
    return 1/(1.0+np.exp(z))

In [ ]:
def feedforward(self,a):
    for b,w in zip(self.biases,self.weights):
        a=sigmoid(np.dot(a,w)+b)
    return a

In [10]:
def SGD(self,training_data,epochs,mini_batch_size,eta,test_data=None):
    if test_data:
        n_test=len(test_data)
    n=len(training_data)
    for j in range(epochs):
        random.shuffle(training_data)
        mini_batches=[
            training_data[k:k+mini_batch_size]
            for k in range(0,n,mini_batch_size)
        ]
        for mini_batch in mini_batches:
            self.update_mini_batch(mini_batch,eta)
        if test_data:
            print("Epoch {0}:{1}/{2}".format(j,self.evaluate(test_data),n_test))
        else:
            print("Epoch {0} is complete".format(j))

In [4]:

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [6]:
def backprop(self, x, y):
        """Return a tuple ``(nabla_b, nabla_w)`` representing the
        gradient for the cost function C_x.  ``nabla_b`` and
        ``nabla_w`` are layer-by-layer lists of numpy arrays, similar
        to ``self.biases`` and ``self.weights``."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        # feedforward
        activation = x
        activations = [x] # list to store all the activations, layer by layer
        zs = [] # list to store all the z vectors, layer by layer
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation)+b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        # backward pass
        delta = self.cost_derivative(activations[-1], y) * \
            sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())
        # Note that the variable l in the loop below is used a little
        # differently to the notation in Chapter 2 of the book.  Here,
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.  It's a renumbering of the
        # scheme in the book, used here to take advantage of the fact
        # that Python can use negative indices in lists.
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        return (nabla_b, nabla_w)


In [7]:
def update_mini_batch(self,mini_batch,eta):
    nabla_b=[np.zeros(b.shape) for b in self.biases]
    nabla_w=[np.zeros(w.shape) for w in self.weights]#place the store the gradient ie the number you input where you multiply 
    # with n and subtract
    for x,y in mini_batch:
        delta_nabla_b, delta_nable_w=self.backprop(x,y)
        nabla_b=[nb+dnb for nb,dnb in zip(nabla_b,delta_nabla_b)]
        nabla_w=[nw+dnw for nw,dnw in zip(nabla_w,delta_nabla_w)]
    self.weights=[w-(eta/len(mini_batch))*nw 
                  for w,nw in zip(self.weights,nabla_w)]
    self.biases=[b-(eta/len(mini_batch))*nb 
                 for b,nb in zip(self.biases,nabla_b)]
    

nabla_b = [0.0] (initial zero)

First example → delta_nabla_b = [0.1]

Second example → delta_nabla_b = [-0.05]

gradient vector

In [12]:
class Neytwork(object):

    def __init__(self, sizes):
        """The list ``sizes`` contains the number of neurons in the
        respective layers of the network.  For example, if the list
        was [2, 3, 1] then it would be a three-layer network, with the
        first layer containing 2 neurons, the second layer 3 neurons,
        and the third layer 1 neuron.  The biases and weights for the
        network are initialized randomly, using a Gaussian
        distribution with mean 0, and variance 1.  Note that the first
        layer is assumed to be an input layer, and by convention we
        won't set any biases for those neurons, since biases are only
        ever used in computing the outputs from later layers."""
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x)
                        for x, y in zip(sizes[:-1], sizes[1:])]

    def feedforward(self, a):
        """Return the output of the network if ``a`` is input."""
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w, a)+b)
        return a

    def SGD(self, training_data, epochs, mini_batch_size, eta,
            test_data=None):
        """Train the neural network using mini-batch stochastic
        gradient descent.  The ``training_data`` is a list of tuples
        ``(x, y)`` representing the training inputs and the desired
        outputs.  The other non-optional parameters are
        self-explanatory.  If ``test_data`` is provided then the
        network will be evaluated against the test data after each
        epoch, and partial progress printed out.  This is useful for
        tracking progress, but slows things down substantially."""
        if test_data: n_test = len(test_data)
        n = len(training_data)
        for j in range(epochs):
            random.shuffle(training_data)
            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in range(0, n, mini_batch_size)]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print("Epoch {0}: {1} / {2}".format(
                    j, self.evaluate(test_data), n_test))
            else:
                print("Epoch {0} complete".format(j))

    def update_mini_batch(self, mini_batch, eta):
        """Update the network's weights and biases by applying
        gradient descent using backpropagation to a single mini batch.
        The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
        is the learning rate."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x, y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
        self.weights = [w-(eta/len(mini_batch))*nw
                        for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb
                       for b, nb in zip(self.biases, nabla_b)]

    def backprop(self, x, y):
        """Return a tuple ``(nabla_b, nabla_w)`` representing the
        gradient for the cost function C_x.  ``nabla_b`` and
        ``nabla_w`` are layer-by-layer lists of numpy arrays, similar
        to ``self.biases`` and ``self.weights``."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        # feedforward
        activation = x
        activations = [x] # list to store all the activations, layer by layer
        zs = [] # list to store all the z vectors, layer by layer
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation)+b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        # backward pass
        delta = self.cost_derivative(activations[-1], y) * \
            sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())
        # Note that the variable l in the loop below is used a little
        # differently to the notation in Chapter 2 of the book.  Here,
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.  It's a renumbering of the
        # scheme in the book, used here to take advantage of the fact
        # that Python can use negative indices in lists.
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        return (nabla_b, nabla_w)

    def evaluate(self, test_data):
        """Return the number of test inputs for which the neural
        network outputs the correct result. Note that the neural
        network's output is assumed to be the index of whichever
        neuron in the final layer has the highest activation."""
        test_results = [(np.argmax(self.feedforward(x)), y)
                        for (x, y) in test_data]
        return sum(int(x == y) for (x, y) in test_results)

    def cost_derivative(self, output_activations, y):
        """Return the vector of partial derivatives \partial C_x /
        \partial a for the output activations."""
        return (output_activations-y)

In [8]:
#### Miscellaneous functions
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [7]:
from tensorflow.keras.datasets import mnist
import numpy as np

def vectorized_result(j):
    e = np.zeros((10,1))
    e[j] = 1.0
    return e

(train_X, train_y), (test_X, test_y) = mnist.load_data()

# Flatten images and normalize
train_X = [np.reshape(x, (784,1))/255.0 for x in train_X]
test_X = [np.reshape(x, (784,1))/255.0 for x in test_X]

# Training data: vectorized output
training_data = list(zip(train_X, [vectorized_result(y) for y in train_y]))

# Split validation data from training
validation_data = list(zip(train_X[:10000], train_y[:10000]))
training_data = training_data[10000:]  # rest for training

# Test data
test_data = list(zip(test_X, test_y))


In [13]:
net=Neytwork([784,30,10])

In [14]:
net.SGD(training_data, 30, 10, 3.0, test_data=test_data)

Epoch 0: 9012 / 10000
Epoch 1: 9206 / 10000
Epoch 2: 9275 / 10000
Epoch 3: 9287 / 10000
Epoch 4: 9335 / 10000
Epoch 5: 9373 / 10000
Epoch 6: 9396 / 10000
Epoch 7: 9404 / 10000
Epoch 8: 9396 / 10000
Epoch 9: 9417 / 10000
Epoch 10: 9432 / 10000
Epoch 11: 9452 / 10000
Epoch 12: 9475 / 10000
Epoch 13: 9469 / 10000
Epoch 14: 9453 / 10000
Epoch 15: 9475 / 10000
Epoch 16: 9457 / 10000
Epoch 17: 9465 / 10000
Epoch 18: 9485 / 10000
Epoch 19: 9466 / 10000
Epoch 20: 9503 / 10000
Epoch 21: 9487 / 10000
Epoch 22: 9482 / 10000
Epoch 23: 9508 / 10000
Epoch 24: 9503 / 10000
Epoch 25: 9484 / 10000
Epoch 26: 9488 / 10000
Epoch 27: 9484 / 10000
Epoch 28: 9497 / 10000
Epoch 29: 9508 / 10000


In [15]:
net=Neytwork([784,100,10])
net.SGD(training_data, 30, 10, 3.0, test_data=test_data)

Epoch 0: 5593 / 10000
Epoch 1: 6431 / 10000
Epoch 2: 6898 / 10000
Epoch 3: 7693 / 10000
Epoch 4: 7703 / 10000
Epoch 5: 7749 / 10000
Epoch 6: 7737 / 10000
Epoch 7: 7733 / 10000
Epoch 8: 7754 / 10000
Epoch 9: 7764 / 10000
Epoch 10: 7792 / 10000
Epoch 11: 7818 / 10000
Epoch 12: 8601 / 10000
Epoch 13: 8654 / 10000
Epoch 14: 8646 / 10000
Epoch 15: 8655 / 10000
Epoch 16: 8680 / 10000
Epoch 17: 8699 / 10000
Epoch 18: 8699 / 10000
Epoch 19: 8699 / 10000
Epoch 20: 8698 / 10000
Epoch 21: 8697 / 10000
Epoch 22: 8697 / 10000
Epoch 23: 8699 / 10000
Epoch 24: 8690 / 10000
Epoch 25: 8700 / 10000
Epoch 26: 8709 / 10000
Epoch 27: 8722 / 10000
Epoch 28: 8719 / 10000
Epoch 29: 8723 / 10000


In [16]:
net=Neytwork([784,10])
net.SGD(training_data, 30, 10, 3.0, test_data=test_data)

Epoch 0: 7312 / 10000
Epoch 1: 7382 / 10000
Epoch 2: 7446 / 10000
Epoch 3: 7469 / 10000
Epoch 4: 7464 / 10000
Epoch 5: 7499 / 10000
Epoch 6: 7507 / 10000
Epoch 7: 7515 / 10000
Epoch 8: 7494 / 10000
Epoch 9: 7493 / 10000
Epoch 10: 7507 / 10000
Epoch 11: 7504 / 10000
Epoch 12: 7518 / 10000
Epoch 13: 7519 / 10000
Epoch 14: 7497 / 10000
Epoch 15: 7515 / 10000
Epoch 16: 7528 / 10000
Epoch 17: 7508 / 10000
Epoch 18: 7523 / 10000
Epoch 19: 7519 / 10000
Epoch 20: 7535 / 10000
Epoch 21: 7505 / 10000
Epoch 22: 7513 / 10000
Epoch 23: 7533 / 10000
Epoch 24: 7547 / 10000
Epoch 25: 7523 / 10000
Epoch 26: 7538 / 10000
Epoch 27: 7529 / 10000
Epoch 28: 7522 / 10000
Epoch 29: 7538 / 10000
