In [111]:
import torch
from torch import tensor

In [45]:
t.__version__

'2.7.1+cu118'

In [46]:
scalar=t.tensor(9)
scalar

tensor(9)

In [47]:
scalar.ndim

0

In [48]:
scalar.item()

9

In [49]:
#count the number of square brackets on left
vector=t.tensor([1,3])
vector.ndim

1

In [50]:
vector.shape

torch.Size([2])

In [51]:
matrix=t.tensor([[4,6],[5,2]])
matrix.ndim

2

In [52]:
matrix.shape

torch.Size([2, 2])

In [53]:
matrix.ndim

2

In [54]:
tensor=t.tensor([[[1,2,3],[3,5,6],[3,4,6]]])

In [55]:
tensor.shape

torch.Size([1, 3, 3])

In [56]:
tensor.ndim

3

In [57]:
random_tensor=t.rand(size=(6,2))

In [58]:
random_tensor

tensor([[0.5562, 0.9975],
        [0.4983, 0.0159],
        [0.4629, 0.1233],
        [0.1552, 0.4359],
        [0.2739, 0.0729],
        [0.9357, 0.7487]])

In [59]:
zeros=t.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
ones=t.ones(size=(3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
arange=t.arange(0,20,1)
arange

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [62]:
zeros=t.zeros_like(arange)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
ones=t.ones_like(arange)
ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [71]:
float_32_tensor=t.tensor([3,6,6],device=None,dtype=t.float32,requires_grad=False)

In [72]:
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [73]:
some_torch=t.rand(3,4)
some_torch.dtype,some_torch.device,some_torch.shape

(torch.float32, device(type='cpu'), torch.Size([3, 4]))

In [74]:
A=t.rand(2,2)
B=t.rand(2,2)

In [75]:
A,B

(tensor([[0.6450, 0.2251],
         [0.3444, 0.0322]]),
 tensor([[0.9567, 0.6859],
         [0.5599, 0.4814]]))

In [77]:
A=A+10
A

tensor([[10.6450, 10.2251],
        [10.3444, 10.0322]])

In [78]:
B=B-10
B

tensor([[-9.0433, -9.3141],
        [-9.4401, -9.5186]])

In [79]:
B=B*10
B

tensor([[-90.4331, -93.1407],
        [-94.4014, -95.1862]])

In [81]:
B=t.div(B,10)
B

tensor([[-9.0433, -9.3141],
        [-9.4401, -9.5186]])

In [83]:
B=t.add(B,10)
B

tensor([[0.9567, 0.6859],
        [0.5599, 0.4814]])

In [84]:
C=A*B
C

tensor([[10.1839,  7.0137],
        [ 5.7914,  4.8293]])

In [85]:
C=A@B
C

tensor([[15.9085, 12.2238],
        [15.5130, 11.9248]])

In [86]:
ct=C.T
ct

tensor([[15.9085, 15.5130],
        [12.2238, 11.9248]])

In [113]:
a=t.rand(2,3)
b=t.rand(2,3)

In [114]:
a@b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

you are transposing them fucka

In [89]:
a@b.T

tensor([[0.8827, 0.9040],
        [0.9131, 0.9234]])

In [90]:
c=t.mm(a,b.T)
c

tensor([[0.8827, 0.9040],
        [0.9131, 0.9234]])

In [96]:
t.manual_seed=42
linear=t.nn.Linear(in_features=2,out_features=6)
linear

Linear(in_features=2, out_features=6, bias=True)

In [102]:
t.max(a),t.min(a)

(tensor(0.8283), tensor(0.1704))

In [104]:
a.type(torch.float32).mean()

tensor(0.4803)

In [105]:
torch.sum(a)

tensor(2.8818)

In [106]:
a

tensor([[0.6806, 0.5050, 0.3230],
        [0.1704, 0.8283, 0.3744]])

In [107]:
torch.argmax(a),torch.argmin(a)

(tensor(4), tensor(3))

see how its just lineraly finds the index

In [108]:
a.dtype

torch.float32

In [110]:
a_float_16=a.type(torch.float16)
a_float_16.dtype

torch.float16