In [150]:
import torch
import torch as t
from torch import tensor
from torch import cuda
import numpy as np
import random

In [6]:
t.__version__

'2.7.1+cu118'

In [7]:
scalar=t.tensor(9)
scalar

tensor(9)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

9

In [10]:
#count the number of square brackets on left
vector=t.tensor([1,3])
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
matrix=t.tensor([[4,6],[5,2]])
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix.ndim

2

In [15]:
tensor=t.tensor([[[1,2,3],[3,5,6],[3,4,6]]])

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor.ndim

3

In [18]:
random_tensor=t.rand(size=(6,2))

In [19]:
random_tensor

tensor([[0.8295, 0.7304],
        [0.5505, 0.5221],
        [0.9909, 0.9581],
        [0.3276, 0.1729],
        [0.8622, 0.5040],
        [0.6888, 0.1079]])

In [20]:
zeros=t.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=t.ones(size=(3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [22]:
arange=t.arange(0,20,1)
arange

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [23]:
zeros=t.zeros_like(arange)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
ones=t.ones_like(arange)
ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
float_32_tensor=t.tensor([3,6,6],device=None,dtype=t.float32,requires_grad=False)

In [26]:
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [27]:
some_torch=t.rand(3,4)
some_torch.dtype,some_torch.device,some_torch.shape

(torch.float32, device(type='cpu'), torch.Size([3, 4]))

In [28]:
A=t.rand(2,2)
B=t.rand(2,2)

In [29]:
A,B

(tensor([[0.1085, 0.1112],
         [0.5120, 0.5140]]),
 tensor([[0.9161, 0.7999],
         [0.2604, 0.7546]]))

In [30]:
A=A+10
A

tensor([[10.1085, 10.1112],
        [10.5120, 10.5140]])

In [31]:
B=B-10
B

tensor([[-9.0839, -9.2001],
        [-9.7396, -9.2454]])

In [32]:
B=B*10
B

tensor([[-90.8386, -92.0013],
        [-97.3961, -92.4543]])

In [33]:
B=t.div(B,10)
B

tensor([[-9.0839, -9.2001],
        [-9.7396, -9.2454]])

In [34]:
B=t.add(B,10)
B

tensor([[0.9161, 0.7999],
        [0.2604, 0.7546]])

In [35]:
C=A*B
C

tensor([[9.2608, 8.0876],
        [2.7373, 7.9335]])

In [36]:
C=A@B
C

tensor([[11.8937, 15.7151],
        [12.3682, 16.3418]])

In [37]:
ct=C.T
ct

tensor([[11.8937, 12.3682],
        [15.7151, 16.3418]])

In [38]:
a=t.rand(2,3)
b=t.rand(2,3)

In [39]:
a@b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

you are transposing them fucka

In [40]:
a@b.T

tensor([[0.4630, 0.6531],
        [0.9796, 0.7039]])

In [41]:
c=t.mm(a,b.T)
c

tensor([[0.4630, 0.6531],
        [0.9796, 0.7039]])

In [99]:
linear=t.nn.Linear(in_features=2,out_features=6)
linear

Linear(in_features=2, out_features=6, bias=True)

In [43]:
t.max(a),t.min(a)

(tensor(0.9876), tensor(0.2367))

In [44]:
a.type(torch.float32).mean()

tensor(0.6144)

In [45]:
torch.sum(a)

tensor(3.6867)

In [46]:
a

tensor([[0.5326, 0.7184, 0.2430],
        [0.2367, 0.9876, 0.9684]])

In [47]:
torch.argmax(a),torch.argmin(a)

(tensor(4), tensor(3))

see how its just lineraly finds the index

In [48]:
a.dtype

torch.float32

In [49]:
a_float_16=a.type(torch.float16)
a_float_16.dtype

torch.float16

In [61]:
x=torch.arange(2,8,1)
x

tensor([2, 3, 4, 5, 6, 7])

In [59]:
x=x.reshape(2,3)

In [60]:
x

tensor([[2, 3, 4],
        [5, 6, 7]])

In [62]:
z=x.view(3,2)
z

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [63]:
z[:,1]=10
z,x

(tensor([[ 2, 10],
         [ 4, 10],
         [ 6, 10]]),
 tensor([ 2, 10,  4, 10,  6, 10]))

view is just a reference

In [64]:
z

tensor([[ 2, 10],
        [ 4, 10],
        [ 6, 10]])

In [67]:
z=z.reshape(6)
z

tensor([ 2, 10,  4, 10,  6, 10])

In [68]:
z_stacked=torch.stack([z,z,z,z],dim=0)
z_stacked

tensor([[ 2, 10,  4, 10,  6, 10],
        [ 2, 10,  4, 10,  6, 10],
        [ 2, 10,  4, 10,  6, 10],
        [ 2, 10,  4, 10,  6, 10]])

In [75]:
x=torch.arange(0,24).reshape(2,4,3)

In [76]:
x[0]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [77]:
x[0][0]

tensor([0, 1, 2])

In [78]:
x[0][1][2]

tensor(5)

In [79]:
x[:]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [81]:
x[:,0,1]

tensor([ 1, 13])

In [86]:
x[:,0,:]

tensor([[ 0,  1,  2],
        [12, 13, 14]])

In [83]:
x[1,2]

tensor([18, 19, 20])

In [89]:
z=torch.arange(1,8)
y=torch.Tensor.numpy(z)
y,z

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [90]:
z=np.arange(1,8)
y=torch.from_numpy(z)
y,z

(tensor([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7]))

In [117]:
torch.random.manual_seed(42)

In [126]:
torch.random.manual_seed(42)
random_tensor_C = torch.rand(3, 4)
torch.random.manual_seed(42)
random_tensor_D = torch.rand(3, 4)
random_tensor_C,random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [127]:
!nvidia-smi

Thu Aug 14 11:45:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   57C    P0             20W /   93W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [128]:
torch.cuda.is_available()

True

In [129]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [130]:
# Count number of devices
torch.cuda.device_count()

1

In [131]:
tensor = torch.tensor([1, 2, 3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [132]:
tensor_on_gpu=tensor.to(device)

In [133]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [134]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [135]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [136]:
tensor_on_gpu,tensor,tensor_back_on_cpu

(tensor([1, 2, 3], device='cuda:0'), tensor([1, 2, 3]), array([1, 2, 3]))

In [138]:
z=torch.arange(0,49).reshape(7,7)
z

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48]])

In [142]:
z11=torch.arange(0,7).reshape(1,7)
z11

tensor([[0, 1, 2, 3, 4, 5, 6]])

In [145]:
z@z11.T

tensor([[ 91],
        [238],
        [385],
        [532],
        [679],
        [826],
        [973]])

In [147]:
torch.random.manual_seed(0)
z=torch.arange(0,49).reshape(7,7)
torch.random.manual_seed(0)
z1=torch.arange(0,7).reshape(1,7)
z,z1

(tensor([[ 0,  1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12, 13],
         [14, 15, 16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25, 26, 27],
         [28, 29, 30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47, 48]]),
 tensor([[0, 1, 2, 3, 4, 5, 6]]))

In [149]:
z@z1.T

tensor([[ 91],
        [238],
        [385],
        [532],
        [679],
        [826],
        [973]])

In [152]:
torch.cuda.manual_seed(1234)

In [156]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a,b

(tensor([[0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000]]),
 tensor([[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742]]))

In [158]:
a_gpu=a.to(device)
a_gpu

tensor([[0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000]], device='cuda:0')

In [159]:
b_gpu=b.to(device)
b_gpu

tensor([[0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742]], device='cuda:0')

In [161]:
c_gpu=a_gpu@b_gpu.T
c_gpu

tensor([[0.2516, 0.3444],
        [0.8257, 1.4509]], device='cuda:0')

In [166]:
c_gpu.argmax(),c_gpu.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [168]:
c_gpu.min(),c_gpu.max()

(tensor(0.2516, device='cuda:0'), tensor(1.4509, device='cuda:0'))

In [175]:
torch.random.manual_seed(7)
dim=torch.rand(1,1,1,10)
dim.shape,dim

(torch.Size([1, 1, 1, 10]),
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]))

In [176]:
new_dim=torch.squeeze(dim)
new_dim.shape,new_dim

(torch.Size([10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))